_id: "449764483313696768"
name: ä½œä¸šæ€æ‰‹ğŸ¥·
description: null
model: gpt-4o
createdAt: 2024-05-26T02:43:29.043Z
updatedAt: 2024-05-26T02:44:42.712Z
createdBy: z1fXXRA3YQTAAkKr4kVTJ6nWZnQm6AFAuNF
updatedBy: z1fXXRA3YQTAAkKr4kVTJ6nWZnQm6AFAuNF
pinnedAt: null
gitType: simple
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: null
