_id: "449764483313696768"
name: ä½œä¸šæ€æ‰‹ğŸ¥·
model: ""
createdAt: 2024-05-26T02:43:29.043Z
updatedAt: 2024-05-26T02:43:29.043Z
createdBy: z1fXXRA3YQTAAkKr4kVTJ6nWZnQm6AFAuNF
updatedBy: z1fXXRA3YQTAAkKr4kVTJ6nWZnQm6AFAuNF
gitType: simple
temperature: 1
topP: 1
